### ISSUE TITLE
Question: Any way to retrieve the generated deployment id?

### ISSUE THREAD

**Issue by mauro-dellachiesa-bl** [newrelic/deployment-marker-action#34]
I was wondering if it is possible to obtain the id of the deployment market the action creates. I would like to use it to query some metrics inside the context of another action's job.

Thanks!

**Comment by jonathanpdx** [comment]
We have some work in progress to handle that use case. Hopefully out next week.

**Comment by JustinLewisNR** [comment]
We've merged a feature into the action to push the deployment id to the github environment. See the updated readme for how to do this.

**Comment by sanderblue** [comment]
Hi @mauro-dellachiesa-bl, this feature has been released in [v2.3.0](https://github.com/newrelic/deployment-marker-action/releases/tag/v2.3.0). If this doesn't solve your use case, please open a new feature request ticket. Thanks! 🙂
